version: "3.9"

services:
  auth-reg:                       
    image: matveyb2005/auth-reg@sha256:010e76ea0d4db883ddb35f221b2a6936cacc1fa61c600f69ad9647d727cf8cab
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always               
