version: "3.9"

services:
  auth-reg:                       
    image: matveyb2005/auth-reg@sha256:55750790650ce64c9b085125f879dde585bcc9852745395efacd5e68e46def3d
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always               
