services:
  auth-reg:                       
    image: matveyb2005/auth-reg:latest
    env_file:
      - .env
    restart: always               
    networks:
      - fyp-default
      
networks:
  fyp-default:
    external: true
