name: Build and Deploy reg-zareg

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: matveyb2005/reg-zareg:latest

  deploy:
    name: Deploy to Server via Docker Compose
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file from secrets
        run: |
          echo "KEY_REGLOG=${{ secrets.KEY_REGLOG }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

      - name: Upload docker-compose.yml to server
        uses: srueda99/scp-action@v13
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          origin: docker-compose.yml
          destination: /FYP/FYP_back/${{ github.event.repository.name }}/docker-compose.yml

      - name: Upload .env to server
        uses: srueda99/scp-action@v13
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          origin: .env
          destination: /FYP/FYP_back/${{ github.event.repository.name }}/.env

      - name: Run Docker Compose on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host:        ${{ secrets.SERVER_HOST }}
          username:    ${{ secrets.SERVER_USERNAME }}
          key:         ${{ secrets.SERVER_KEY }}
          port:        ${{ secrets.SERVER_PORT }}
          script: |
            mkdir -p /FYP/FYP_back/${{ github.event.repository.name }}
            cd /FYP/FYP_back/${{ github.event.repository.name }}
            docker-compose pull
            docker-compose up -d 
