name: Build and Deploy reg-zareg

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image_digest: ${{ steps.build_and_push.outputs.digest }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag based on commit SHA
        id: tag
        run: echo "TAG=matveyb2005/auth-reg:${{ github.sha }}" >> $GITHUB_ENV  

      - name: Build and push image
        id: build_and_push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.TAG }}  

      - name: Show image digest
        run: echo "Image digest is ${{ steps.build_and_push.outputs.digest }}"  

  deploy:
    name: Deploy to Server via Docker Compose
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file from secrets
        run: |
          echo "KEY_REGLOG=${{ secrets.KEY_REGLOG }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

      - name: Replace image tag with digest in docker-compose.yaml
        run: |
          DIGEST=${{ steps.build_and_push.outputs.digest }}  # Получаем digest
          echo "Using image digest: $DIGEST"
          sed -i "s|matveyb2005/auth-reg:latest|matveyb2005/auth-reg@$DIGEST|g" docker-compose.yaml  # Заменяем на актуальный digest

      - name: Upload docker-compose.yaml to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_NAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: ./docker-compose.yaml
          target: /FYP/

      - name: Upload .env to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_NAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: .env
          target: /FYP/

      - name: Run Docker Compose on server
        uses: nekiro/ssh-job@v1.0.5
        with:
          host:        ${{ secrets.SERVER_HOST }}
          user:        ${{ secrets.SERVER_NAME }}
          key:         ${{ secrets.SERVER_KEY }}
          port:        ${{ secrets.SERVER_PORT }}
          password:    ${{ secrets.SERVER_PASSWORD }}
          command: |
            mkdir -p /FYP/FYP_back/${{ github.event.repository.name }}
            mv /FYP/docker-compose.yaml /FYP/FYP_back/
            mv /FYP/.env /FYP/FYP_back/
            cd /FYP/FYP_back/
            docker-compose pull
            docker-compose up -d --force-recreate
